### ISSUE TITLE
Alias File type for Seed of Yggdrasil

### ISSUE THREAD

**Issue by zably** [theBowja/PoringWorldBot#15]
Just randomly noticed that on line 227 of the alias file "Sedd of Yggdrasil" looks to be mistyped.

Shows up on Poring World as "seed" for me, but honestly not sure if it's a typo on their end somewhere and this is actually correct.

![image](https://user-images.githubusercontent.com/7295661/133953275-27cc03d8-5ad0-4b9c-9843-1fae1fdb8a6d.png)

**Comment by theBowja** [comment]
You're right! Thanks!
