### ISSUE TITLE
Can't use the bot

### ISSUE THREAD

**Issue by lfec** [theBowja/PoringWorldBot#7]
Yesterday i noticed the bot wasn't responding to any command, neither !pwb alive nor !pwb help, no reaction at all, but still sending me my already registered requests.
Old Requests OK, New Requests, not ok.

I tried removing and inviting the bot again, but this has not solved my problem.

Coud you look into it? Thanks

**Comment by theBowja** [comment]
For the past two days my internet was down so the bot wasn't online. I just got it fixed.

Reinvite the bot while it is still online (you can check by joining my discord and checking the member list for the bot).

Tell me if you're still having troubles after.

**Comment by lfec** [comment]
The bot is working fine now.
Thank you.
